### PR TITLE
Add explanation about argument name uniqueness.

### PR DESCRIPTION
**Pull request by dugenkui03**
Details in #739.

### CODE REVIEW

**Review by mjmahone — COMMENTED** [review]
This looks good to go for the next WG, in my opinion: we should merge it in!

**Comment by benjie** [comment]
Can someone add it to the next WG agenda?

**Comment by benjie** [comment]
I've merged the latest, did some tiny edits, and have added it to the next WG.

**Review by mjmahone — APPROVED** [review]
This feels clear

**Pull request merged**
