### PR TITLE
SDL's to omit directives from its printer

### LINKED ISSUE #814: Articulate that built-in directives not be returned from introspection results
Much like the spec currently states ["all built‐in scalars must be omitted for brevity."](https://spec.graphql.org/draft/#sel-GAHXLHABAB_DnhW).

I'd like to propose we say something similar to that, but specifically referencing this for built-in directives, namely the `@skip` and `@include` etc.. 

In the past I have been told that "we return that in the introspection so you know what the capabilities are", my answer to that is "if its in the spec, the capability SHOULD already be there, no need to tell me that". 

Granted this is an opinion of the matter, but just raising in case there is sentiment to guide what we do about umbrella built-in's, and not just built-in scalars—as this would mean tighter cohesion between different server implementations.

---

I would be open to spearheading this initiative, but will need to be hand held a tad making a PR.

### PR DESCRIPTION
**Pull request by maraisr**
fixes #814

### CODE REVIEW

**Comment by maraisr** [comment]
Closing due to no appetite for it. see https://github.com/graphql/graphql-spec/issues/814#issuecomment-760700953

**Comment by benjie** [comment]
@maraisr To add some justification for not adding this change, new directives such as `@defer` and `@stream` are being added to the GraphQL Spec (i.e. they are "built in"), but support for them is optional - clients can use introspection to see whether the directive exists or not to see if the feature is supported. So I think it's worth continuing to include directives in the printed schema/introspection results.

**Comment by michaelstaib** [comment]
@benjie that was my first thinking on this. With scalars it is different since they are pretty stable and thus can be omitted from the GraphQL SDL.

**Comment by maraisr** [comment]
This is ridiculous. Sorry. But why should schema authors keep a dictionary of directives they must include? And remember to update them and all the rest of it. And why isn't this true for scalars then also?

**Comment by benjie** [comment]
> why should schema authors keep a dictionary of directives they must include?

They don't need to, they only need to keep a list of the optional or custom directives they explicitly want to support. Mandated directives (such as `@skip` and `@include`) do not need to be specified explicitly, support will be added by the GraphQL library you're using (such as graphql-js). The following is a valid schema that supports `@skip` and `@include` (but neither `@defer` nor `@stream`):

```graphql
type Query {
  a: Int
}
```


> And why isn't this true for scalars then also?

A schema states whether or not it supports a scalar by whether or not the scalar exists in the schema's type system, this is not the same for directives since they are client-specified so the schema has to explicitly indicate if an optional directive (builtin or otherwise) is supported or not.

**Comment by michaelstaib** [comment]
@benjie I think the question that @maraisr really has here. When a server prints a schema as SDL, should these built-in directives be printed. The PR I think aims to introduce a note like for the built-in scalars. 

> When representing a GraphQL schema using the type system definition language, all built‐in scalars must be omitted for brevity.

http://spec.graphql.org/draft/#sec-Scalars.Built-in-Scalars

**Comment by maraisr** [comment]
@benjie what i was referencing was that `@skip` must be kept in a dictionary. Because the spec doesn't say that _only custom ones_ must be included.

**Comment by benjie** [comment]
@michaelstaib Agreed; the issue is the term "built in" in this change since `@stream` and `@defer` will effectively be "built in" to the GraphQL spec, but support for them is optional. Built in mandatory directives can/should be/are omitted from SDL, but optional and custom directives must be specified.

<details>
<summary>Code showing the reference implementation already omits `@include` and `@skip` from printed SDL</summary>

```js
const {
  GraphQLSchema,
  GraphQLInt,
  GraphQLObjectType,
  printSchema,
  validateSchema,
  graphqlSync,
} = require("graphql");

const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: "Query",
    fields: {
      a: {
        type: GraphQLInt,
      },
    },
  }),
});

const validationResult = validateSchema(schema);
if (validationResult.length) {
  throw new Error(
    `Invalid schema!\n${validationResult.map(e => e.message).join("\n")}`
  );
}

console.log(printSchema(schema));

console.log(
  JSON.stringify(
    graphqlSync(
      schema,
      `{
  __schema {
    directives {
      name
    }
  }
}`
    ),
    null,
    2
  )
);
```

Printed schema:

```graphql
type Query {
  a: Int
}
```

Directive introspection results:

```json
{
  "data": {
    "__schema": {
      "directives": [
        {
          "name": "include"
        },
        {
          "name": "skip"
        },
        {
          "name": "deprecated"
        },
        {
          "name": "specifiedBy"
        }
      ]
    }
  }
}
```

</details>

I definitely support a change that says that `@include` and `@skip` should be omitted from SDL like scalars are (assuming that doesn't already exist in the spec), but the specific change proposed here will cause issues for `@stream`, `@defer` and potentially other directives in future.

**Comment by maraisr** [comment]
How would you like me to proceed? Change my pr to state that built in required directives be omitted from the sdl?

**Comment by michaelstaib** [comment]
@maraisr @benjie  should we reopen and formulate this one then?

**Comment by michaelstaib** [comment]
I think the PR should state clearly in the description the intension and the state clearly like with built-in scalars when thinks can be omitted. I think @benjie already stated it very nicely.

**Pull request closed without merging**
