### PR TITLE
__Type represents all types in the system

### PR DESCRIPTION
**Pull request by benjie**
In https://github.com/graphql/graphql-spec/pull/733#discussion_r466615699 @leebyron noted:

> maybe we should just say: "It represents all types in the system."

I wasn't quite comfortable with what "all types" meant - whether it was inclusive or exclusive of modified types. The second paragraph implied exclusive due to the `also` but this didn't sit quite right with me. At first I edited it to say "all _named_ types in the system", but felt it made the second paragraph feel a bit disjoint.

I've further modified the text and feel it's much clearer now.

I'm trying to move discussions like this out of the Tagged type spec itself, to keep the signal to noise ratio high (and figure they're useful mods for any future type additions anyway, keeping maintenance burden down).

### CODE REVIEW

**Comment by benjie** [comment]
Incidentally we consistently refer to "type modifier" not as the concept of `List`/`NonNull` itself, but as a specific instance of these concepts applied to a specific type; I've tried to maintain this in this PR. I'd prefer to call `List`/`NonNull` themselves "type modifiers", and `List(NamedType)` a "modified type" - if this seems reasonable I'm happy to make the relevant edits.

**Comment by benjie** [comment]
@leebyron Could I get your eyes on this?

**Comment by leebyron** [comment]
Thanks for the reminder. I tagged it so I don't lose it :)

Let me give this a closer read when I get a free moment

**Comment by Muftaa** [comment]
-0--popk

**Review by Muftaa — APPROVED** [review]

**Comment by benjie** [comment]
@leebyron Gentle nudge :wink:

**Comment by benjie** [comment]
LGTM @leebyron :+1:

**Pull request merged**
