### PR TITLE
Fix typos in the GraphQL Defer and Stream Directives RFC

### PR DESCRIPTION
**Pull request by kyarik**
- Add missing backticks around `@stream` and `@defer`.
- Fix some misspelled words.

### CODE REVIEW

**Comment by benjie** [comment]
cc @robrichard

**Review by robrichard — APPROVED** [review]

**Comment by benjie** [comment]
@kyarik If you sign the CLA (see the message above) we can get this fix merged :+1:

**Comment by kyarik** [comment]
@benjie Done :+1:

**Comment by benjie** [comment]
Thanks! :raised_hands:

**Pull request merged**
