### PR TITLE
Rename VariableDefinitions to VariablesDefinition

### LINKED ISSUE #915: Question about naming
Consider those parts of the spec for list nodes in GraphQL grammar:

http://spec.graphql.org/October2021/#ArgumentsDefinition
http://spec.graphql.org/October2021/#InputFieldsDefinition
http://spec.graphql.org/October2021/#FieldsDefinition
http://spec.graphql.org/October2021/#EnumValuesDefinition

_s_ before _Definition_

but for variables

http://spec.graphql.org/October2021/#VariableDefinitions

_s_ after _Definition_ . 

Was it done intentionally?

### PR DESCRIPTION
**Pull request by sungam3r**
fixes #915

### CODE REVIEW

**Comment by sungam3r** [comment]
Should I revert `changelogs/October2021.md` ?

**Comment by benjie** [comment]
Yes, revert that 👍

**Comment by sungam3r** [comment]
done

**Comment by sungam3r** [comment]
done

**Review by benjie — APPROVED** [review]

**Pull request merged**
